### ISSUE TITLE
How to convert input to luxon.DateTime for DateTime columns

### ISSUE THREAD

**Issue by flyinglimao** [SoftwareBrothers/adminjs-adonis#1]
Hi, I started using Adminjs and Adonis, and encountered the problem that when I update a record (with built-in `createdAt`, `updatedAt`), I got the error:
```
"Invalid value for \"User.createdAt\". It must be an instance of \"luxon.DateTime\""
```

I guess the cause is that the form input is directly passed to Lucid in string type, while Lucid requires it to be formatted to `DateTime` type.
I looked over documents in Adminjs, but I didn't find a way to format them.

Thank you

**Comment by dziraf** [comment]
@flyinglimao I'm on vacation until next week so I can look into this on Monday but it seemed to work for me when I'd tested the integration.

1. Shouldn't timestamps (createdAt, updatedAt) be updated automatically?
2. If they're set to be updated automatically, could you try remove them from payload using a `before` hook in `edit`?

before hook:
```ts
const stripPayloadFromRequest = (...fields) => (request) => {
  const { payload = {} } = request;
  
  if (request.method === 'get') return request;
  
  request.payload = Object.entries(payload).reduce((memo, [key, value]) => {
    if (!fields.includes(key)) {
      memo[key] = value;
    }
    
    return memo;
  }, {});
  
  return request;
}
```

resource config:
```ts
{
  resource: new LucidResource(Model),
  options: {
    actions: {
      edit: {
        before: [stripPayloadFromRequest('createdAt', 'updatedAt')],
      },
    },
  }.
}
```

**Comment by flyinglimao** [comment]
Hi, @dziraf 
Thank you, the solution works.
I'm wondering if it could result from the naming strategy of lucid, which turns columnName into a snake case.
![CleanShot 2024-02-23 at 01 17 49](https://github.com/SoftwareBrothers/adminjs-adonis/assets/11978467/87638a27-67ce-4c7e-8532-bff8a39cad64)

**Comment by flyinglimao** [comment]
I found it works after I switched to PostgreSQL from SQLite, closing it
